version: '3'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=discorddb
    ports:
      - '5432:5432'
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/frontend
    ports:
      - '3000:3000'
      - '24678:24678' # HMR port
    depends_on:
      - redis
      - postgres
